"""Expose the decomposed environment-profile implementation package."""

from __future__ import annotations

from .compiler import LongTermEnvironmentProfileCompiler
from .constants import (
    _BASELINE_KINDS,
    _DEFAULT_ACUTE_EMPIRICAL_Q,
    _DEFAULT_ACUTE_Z_THRESHOLD,
    _DEFAULT_BASELINE_DAYS,
    _DEFAULT_DAY_START_HOUR,
    _DEFAULT_DRIFT_MIN_DAYS,
    _DEFAULT_DRIFT_MIN_SIGMA,
    _DEFAULT_EPOCH_MINUTES,
    _DEFAULT_HISTORY_DAYS,
    _DEFAULT_IQR_MULTIPLIER,
    _DEFAULT_LONG_BASELINE_DAYS,
    _DEFAULT_MIN_BASELINE_DAYS,
    _DEFAULT_MIN_COVERAGE_RATIO,
    _DEFAULT_NIGHT_START_HOUR,
    _DEFAULT_REGIME_ACCEPT_DAYS,
    _DEFAULT_TIMEZONE_NAME,
    _DEFAULT_TRANSITION_WINDOW_S,
    _HEALTH_SIGNAL_TYPE,
    _MAX_SOURCE_EVENT_IDS,
    _MOTION_SIGNAL_TYPE,
    _SMART_HOME_ENVIRONMENT_DOMAIN,
    _WEEKDAY_CLASSES,
)
from .helpers import (
    _coerce_float,
    _coerce_mapping,
    _cosine_similarity,
    _entropy_from_counts,
    _ewma,
    _normalize_datetime,
    _normalize_slug,
    _normalize_text,
    _parse_source_event_datetime,
    _resolve_timezone,
    _tokenize_identifier,
    _weekday_class,
)
from .models import (
    SmartHomeEnvironmentBaseline,
    SmartHomeEnvironmentBaselineStat,
    SmartHomeEnvironmentChangePoint,
    SmartHomeEnvironmentDayProfile,
    SmartHomeEnvironmentDeviation,
    SmartHomeEnvironmentDeviationEvent,
    SmartHomeEnvironmentDeviationMetric,
    SmartHomeEnvironmentEpoch,
    SmartHomeEnvironmentEvent,
    SmartHomeEnvironmentNode,
    SmartHomeEnvironmentQualityState,
    SmartHomeEnvironmentRegime,
)

__all__ = [
    "LongTermEnvironmentProfileCompiler",
    "SmartHomeEnvironmentBaseline",
    "SmartHomeEnvironmentBaselineStat",
    "SmartHomeEnvironmentChangePoint",
    "SmartHomeEnvironmentDayProfile",
    "SmartHomeEnvironmentDeviation",
    "SmartHomeEnvironmentDeviationEvent",
    "SmartHomeEnvironmentDeviationMetric",
    "SmartHomeEnvironmentEpoch",
    "SmartHomeEnvironmentEvent",
    "SmartHomeEnvironmentNode",
    "SmartHomeEnvironmentQualityState",
    "SmartHomeEnvironmentRegime",
    "_BASELINE_KINDS",
    "_DEFAULT_ACUTE_EMPIRICAL_Q",
    "_DEFAULT_ACUTE_Z_THRESHOLD",
    "_DEFAULT_BASELINE_DAYS",
    "_DEFAULT_DAY_START_HOUR",
    "_DEFAULT_DRIFT_MIN_DAYS",
    "_DEFAULT_DRIFT_MIN_SIGMA",
    "_DEFAULT_EPOCH_MINUTES",
    "_DEFAULT_HISTORY_DAYS",
    "_DEFAULT_IQR_MULTIPLIER",
    "_DEFAULT_LONG_BASELINE_DAYS",
    "_DEFAULT_MIN_BASELINE_DAYS",
    "_DEFAULT_MIN_COVERAGE_RATIO",
    "_DEFAULT_NIGHT_START_HOUR",
    "_DEFAULT_REGIME_ACCEPT_DAYS",
    "_DEFAULT_TIMEZONE_NAME",
    "_DEFAULT_TRANSITION_WINDOW_S",
    "_HEALTH_SIGNAL_TYPE",
    "_MAX_SOURCE_EVENT_IDS",
    "_MOTION_SIGNAL_TYPE",
    "_SMART_HOME_ENVIRONMENT_DOMAIN",
    "_WEEKDAY_CLASSES",
    "_coerce_float",
    "_coerce_mapping",
    "_cosine_similarity",
    "_entropy_from_counts",
    "_ewma",
    "_normalize_datetime",
    "_normalize_slug",
    "_normalize_text",
    "_parse_source_event_datetime",
    "_resolve_timezone",
    "_tokenize_identifier",
    "_weekday_class",
]
