# Build Twinr's on-device Crazyflie failsafe as an out-of-tree firmware app.

CRAZYFLIE_BASE ?= ../..
OOT := $(realpath $(dir $(lastword $(MAKEFILE_LIST))))
OOT_CONFIG := $(OOT)/app-config

include $(CRAZYFLIE_BASE)/tools/make/oot.mk
