"""Persist and retrieve midterm reflection packets.

This module provides ``LongTermMidtermStore``, the JSON-backed store for
midterm packets generated by long-term reflection. Import
``LongTermMidtermStore`` from this module or via ``twinr.memory.longterm``.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
import json
import logging
import os
from pathlib import Path
import stat
from threading import Lock
import tempfile
from contextlib import suppress
from twinr.agent.base_agent.config import TwinrConfig
from twinr.memory.chonkydb.client import chonkydb_data_path
from twinr.memory.fulltext import FullTextDocument, FullTextSelector
from twinr.memory.longterm.core.cooperative_abort import LongTermOperationCancelledError
from twinr.memory.longterm.core.models import LongTermMidtermPacketV1, LongTermReflectionResultV1
from twinr.memory.longterm.reasoning.turn_continuity import turn_continuity_recall_hints
from twinr.memory.longterm.storage._remote_midterm import LongTermRemoteMidtermState
from twinr.memory.longterm.storage.remote_state import LongTermRemoteUnavailableError
from twinr.memory.longterm.storage.remote_state import LongTermRemoteStateStore
from twinr.text_utils import retrieval_terms


_MIDTERM_STORE_SCHEMA = "twinr_memory_midterm_store"
_MIDTERM_STORE_VERSION = 1
_DEFAULT_RETRIEVAL_LIMIT = 3
_CROSS_SERVICE_READ_MODE = 0o644
_REFLECTION_TURN_CONTINUITY_PRESERVE_LIMIT = 4

# AUDIT-FIX(#8): Add module-level logging so storage recovery paths are diagnosable in production.
LOGGER = logging.getLogger(__name__)


def _normalize_text(value: str | None) -> str:
    """Collapse arbitrary text-like input to normalized single-spaced text."""

    return " ".join(str(value or "").split()).strip()


def _normalize_limit(limit: int) -> int:
    """Coerce a retrieval limit to a bounded non-negative integer."""

    # AUDIT-FIX(#7): Honor explicit zero/negative limits as "return nothing" and log invalid caller input.
    if not isinstance(limit, int):
        LOGGER.warning(
            "Invalid midterm packet limit %r; falling back to default=%d",
            limit,
            _DEFAULT_RETRIEVAL_LIMIT,
        )
        return _DEFAULT_RETRIEVAL_LIMIT
    return max(0, limit)


def _safe_retrieval_terms(value: str) -> set[str]:
    """Tokenize retrieval text and fail closed to an empty token set."""

    # AUDIT-FIX(#5): Retrieval tokenization must fail closed to an empty token-set instead of aborting memory lookup.
    try:
        return {term for term in retrieval_terms(value) if isinstance(term, str) and not term.isdigit()}
    except Exception:
        LOGGER.warning("Failed to tokenize midterm retrieval text", exc_info=True)
        return set()


def _query_match_terms(query_terms: set[str]) -> set[str]:
    """Prefer content-bearing query terms over auxiliary-word-only overlap."""

    if not query_terms:
        return set()
    informative = {
        term
        for term in query_terms
        if isinstance(term, str) and term and (term.isdigit() or len(term) >= 4)
    }
    return informative or query_terms


def _has_query_overlap(*, query_terms: set[str], document_terms: set[str]) -> bool:
    """Return whether document terms overlap one query through exact or compound matches."""

    informative_query_terms = _query_match_terms(query_terms)
    informative_document_terms = _query_match_terms(document_terms)
    if not informative_query_terms or not informative_document_terms:
        return False
    if informative_query_terms.intersection(informative_document_terms):
        return True
    for query_term in informative_query_terms:
        for document_term in informative_document_terms:
            if query_term in document_term or document_term in query_term:
                return True
    return False


def _read_json_object(path: Path) -> dict[str, object] | None:
    """Read one JSON object from disk if the file is a safe regular file."""

    flags = os.O_RDONLY
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW

    try:
        fd = os.open(path, flags)
    except FileNotFoundError:
        return None
    except OSError:
        # AUDIT-FIX(#4): Treat file-open failures as recoverable load errors instead of crashing the caller.
        LOGGER.warning("Failed to open midterm store file %s", path, exc_info=True)
        return None

    try:
        # AUDIT-FIX(#4): Refuse symlinked/non-regular files to reduce local file-system redirection risk.
        stat_result = os.fstat(fd)
        if not stat.S_ISREG(stat_result.st_mode):
            raise OSError(f"Refusing to read non-regular midterm store file: {path}")

        chunks: list[bytes] = []
        while True:
            chunk = os.read(fd, 64 * 1024)
            if not chunk:
                break
            chunks.append(chunk)
    except OSError:
        LOGGER.warning("Failed to read midterm store file %s", path, exc_info=True)
        return None
    finally:
        os.close(fd)

    try:
        loaded = json.loads(b"".join(chunks).decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        LOGGER.warning("Invalid JSON in midterm store file %s", path, exc_info=True)
        return None

    if not isinstance(loaded, dict):
        LOGGER.warning("Ignoring non-object midterm store payload from %s", path)
        return None

    return dict(loaded)


def _packet_updated_at(packet: LongTermMidtermPacketV1) -> datetime:
    """Return one timezone-safe packet timestamp for bounded recency ranking."""

    updated_at = packet.updated_at
    if updated_at.tzinfo is None or updated_at.tzinfo.utcoffset(updated_at) is None:
        return updated_at.replace(tzinfo=timezone.utc)
    return updated_at.astimezone(timezone.utc)


def _fsync_directory(path: Path) -> None:
    """Flush a directory entry to disk after replacing a packet snapshot."""

    directory_fd = os.open(path, os.O_RDONLY)
    try:
        os.fsync(directory_fd)
    finally:
        os.close(directory_fd)


def _write_json_atomic(path: Path, payload: dict[str, object]) -> None:
    """Write a midterm payload atomically and durably to disk."""

    path.parent.mkdir(parents=True, exist_ok=True)
    serialized = json.dumps(payload, ensure_ascii=False, indent=2)
    temp_name: str | None = None

    try:
        # AUDIT-FIX(#1): Use a unique temp file in the target directory to avoid .tmp collisions across writers.
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=str(path.parent),
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temp_name = handle.name
            handle.write(serialized)
            handle.flush()
            os.fchmod(handle.fileno(), _CROSS_SERVICE_READ_MODE)
            # AUDIT-FIX(#1): Flush file contents before replace so sudden power loss is less likely to drop state.
            os.fsync(handle.fileno())

        os.replace(temp_name, path)
        os.chmod(path, _CROSS_SERVICE_READ_MODE)
        temp_name = None
        # AUDIT-FIX(#1): Flush the directory entry so the rename itself is durable on Linux-class filesystems.
        _fsync_directory(path.parent)
    finally:
        if temp_name is not None:
            with suppress(FileNotFoundError):
                os.unlink(temp_name)


def _validate_payload(payload: object, *, source: str) -> dict[str, object] | None:
    """Validate one raw midterm payload before model deserialization."""

    if payload is None:
        # Missing local caches or fresh remote namespaces are absence, not malformed payloads.
        return None

    # AUDIT-FIX(#3): Validate container type and schema metadata before handing data to model loaders.
    if not isinstance(payload, dict):
        LOGGER.warning("Ignoring invalid midterm payload from %s because it is not a JSON object", source)
        return None

    schema = payload.get("schema")
    if schema not in (None, _MIDTERM_STORE_SCHEMA):
        LOGGER.warning(
            "Ignoring midterm payload from %s due to schema mismatch: %r != %r",
            source,
            schema,
            _MIDTERM_STORE_SCHEMA,
        )
        return None

    version = payload.get("version")
    if version not in (None, _MIDTERM_STORE_VERSION):
        LOGGER.warning(
            "Ignoring midterm payload from %s due to version mismatch: %r != %r",
            source,
            version,
            _MIDTERM_STORE_VERSION,
        )
        return None

    items = payload.get("packets", [])
    if not isinstance(items, list):
        LOGGER.warning("Ignoring midterm payload from %s because packets is not a list", source)
        return None

    return dict(payload)


@dataclass(slots=True)
class LongTermMidtermStore:
    """Persist and query midterm packets for short-horizon recall.

    The store keeps a local JSON snapshot authoritative on disk and can mirror
    it to ``LongTermRemoteStateStore`` in remote-primary mode. Retrieval stays
    read-only and bounded by caller-provided limits.
    """

    base_path: Path
    remote_state: LongTermRemoteStateStore | None = None
    _lock: Lock = field(default_factory=Lock, repr=False)
    _remote_midterm: LongTermRemoteMidtermState = field(init=False, repr=False)

    packet_type = LongTermMidtermPacketV1

    def __post_init__(self) -> None:
        """Normalize and validate the configured snapshot directory."""

        # AUDIT-FIX(#6): Normalize and validate the configured base path early so misconfiguration fails deterministically.
        normalized_base_path = Path(self.base_path).expanduser().resolve(strict=False)
        if normalized_base_path.exists() and not normalized_base_path.is_dir():
            raise ValueError(f"LongTermMidtermStore base_path must be a directory: {normalized_base_path}")
        self.base_path = normalized_base_path
        self._remote_midterm = LongTermRemoteMidtermState(self.remote_state)

    @classmethod
    def from_config(cls, config: TwinrConfig) -> "LongTermMidtermStore":
        """Build a midterm store rooted at the configured memory path."""

        return cls(
            base_path=chonkydb_data_path(config),
            remote_state=LongTermRemoteStateStore.from_config(config),
        )

    @property
    def packets_path(self) -> Path:
        """Return the local snapshot path for midterm packets."""

        return self.base_path / "twinr_memory_midterm_v1.json"

    def ensure_remote_snapshot(self) -> bool:
        """Bootstrap the remote midterm current-head state when it is still missing."""

        if not self._remote_midterm.enabled():
            return False
        local_packets = self._load_packets_from_payload(
            self._load_local_payload(),
            source=str(self.packets_path),
        )
        return self._remote_midterm.ensure_seeded(packets=local_packets)

    def ensure_remote_snapshot_for_readiness(self) -> bool:
        """Bootstrap remote midterm state without seeding an empty fresh namespace."""

        if not self._remote_midterm.enabled():
            return False
        local_packets = self._load_packets_from_payload(
            self._load_local_payload(),
            source=str(self.packets_path),
        )
        if local_packets:
            return self._remote_midterm.ensure_seeded(packets=local_packets)
        current_head = self._remote_midterm.probe_current_head()
        if isinstance(current_head, Mapping):
            return False
        return False

    def probe_remote_current_head(self) -> dict[str, object] | None:
        """Probe the fixed-URI remote midterm current head without hydrating packets."""

        if not self._remote_midterm.enabled():
            return None
        payload = self._remote_midterm.probe_current_head()
        return dict(payload) if isinstance(payload, Mapping) else None

    def load_remote_current_head(self) -> dict[str, object] | None:
        """Load the authoritative remote midterm current head payload."""

        if not self._remote_midterm.enabled():
            return None
        payload = self._remote_midterm.current_head_payload()
        return dict(payload) if isinstance(payload, Mapping) else None

    def probe_remote_current_head_for_readiness(self) -> dict[str, object] | None:
        """Probe the remote midterm current head, accepting a fresh empty namespace."""

        payload = self.probe_remote_current_head()
        if isinstance(payload, Mapping):
            return dict(payload)
        return self._synthetic_empty_current_head_for_readiness()

    def load_remote_current_head_for_readiness(self) -> dict[str, object] | None:
        """Load the remote midterm current head, accepting a fresh empty namespace."""

        payload = self.load_remote_current_head()
        if isinstance(payload, Mapping):
            return dict(payload)
        return self._synthetic_empty_current_head_for_readiness()

    def remote_current_packet_ids(self) -> tuple[str, ...]:
        """Return packet ids currently referenced by the remote midterm head."""

        if not self._remote_midterm.enabled():
            return ()
        return self._remote_midterm.current_packet_ids()

    def load_packets(self) -> tuple[LongTermMidtermPacketV1, ...]:
        """Load all valid midterm packets from the current snapshot."""

        return self._load_packets_from_payload(self._load_payload(), source=str(self.packets_path))

    def save_packets(self, *, packets: tuple[LongTermMidtermPacketV1, ...]) -> None:
        """Persist one complete midterm packet snapshot.

        Args:
            packets: Packets to serialize into the local snapshot and optional
                remote mirror.
        """

        with self._lock:
            payload = {
                "schema": _MIDTERM_STORE_SCHEMA,
                "version": _MIDTERM_STORE_VERSION,
                "packets": [item.to_payload() for item in sorted(packets, key=lambda row: row.packet_id)],
            }
            # AUDIT-FIX(#2): Always persist locally first because the device is file-backed and the network is intermittent.
            _write_json_atomic(self.packets_path, payload)

            if self.remote_state is not None and self.remote_state.enabled:
                try:
                    # AUDIT-FIX(#2): The remote midterm authority now lives in typed packet records plus a fixed current head.
                    self._remote_midterm.save_packets(packets=packets)
                except LongTermOperationCancelledError:
                    raise
                except LongTermRemoteUnavailableError:
                    if self.remote_state.required:
                        raise
                    LOGGER.warning(
                        "Failed to replicate midterm current-head state remotely; local cache at %s was kept",
                        self.packets_path,
                        exc_info=True,
                    )
                except Exception:
                    LOGGER.warning(
                        "Failed to replicate midterm current-head state remotely; local cache at %s was kept",
                        self.packets_path,
                        exc_info=True,
                    )

    def _empty_payload(self) -> dict[str, object]:
        return {
            "schema": _MIDTERM_STORE_SCHEMA,
            "version": _MIDTERM_STORE_VERSION,
            "packets": [],
        }

    def _synthetic_empty_current_head_for_readiness(self) -> dict[str, object] | None:
        """Return one read-only empty current-head payload for fresh namespaces."""

        local_payload = self._load_local_payload()
        local_packets = self._load_packets_from_payload(local_payload, source=str(self.packets_path))
        if local_packets:
            return None
        if isinstance(local_payload, Mapping):
            return dict(local_payload)
        return self._payload_from_packets(
            packets=(),
            written_at="1970-01-01T00:00:00+00:00",
        )

    def apply_reflection(self, result: LongTermReflectionResultV1) -> None:
        """Persist the midterm packets emitted by one reflection result."""

        existing_packets = self.load_packets()
        preserved_packets = self._merged_packets(
            primary=self._matching_packets(
                existing_packets,
                attribute_key="persistence_scope",
                attribute_value="restart_recall",
            ),
            secondary=self._latest_matching_packets(
                existing_packets,
                attribute_key="persistence_scope",
                attribute_value="turn_continuity",
                limit=_REFLECTION_TURN_CONTINUITY_PRESERVE_LIMIT,
            ),
        )
        self.save_packets(
            packets=self._merged_packets(
                primary=result.midterm_packets,
                secondary=preserved_packets,
            )
        )

    def replace_packets_with_attribute(
        self,
        *,
        packets: tuple[LongTermMidtermPacketV1, ...],
        attribute_key: str,
        attribute_value: object,
    ) -> None:
        """Replace one scoped packet subset while preserving all others."""

        existing_packets = tuple(
            packet
            for packet in self.load_packets()
            if self._packet_attribute(packet, attribute_key) != attribute_value
        )
        self.save_packets(packets=self._merged_packets(primary=packets, secondary=existing_packets))

    def save_packets_preserving_attribute(
        self,
        *,
        packets: tuple[LongTermMidtermPacketV1, ...],
        attribute_key: str,
        attribute_value: object,
    ) -> None:
        """Save a primary packet set while preserving one explicitly scoped subset."""

        preserved_packets = tuple(
            packet
            for packet in self.load_packets()
            if self._packet_attribute(packet, attribute_key) == attribute_value
        )
        self.save_packets(packets=self._merged_packets(primary=packets, secondary=preserved_packets))

    def _matching_packets(
        self,
        packets: tuple[LongTermMidtermPacketV1, ...],
        *,
        attribute_key: str,
        attribute_value: object,
    ) -> tuple[LongTermMidtermPacketV1, ...]:
        """Return all packets whose attribute exactly matches one scoped value."""

        return tuple(
            packet
            for packet in packets
            if self._packet_attribute(packet, attribute_key) == attribute_value
        )

    def _latest_matching_packets(
        self,
        packets: tuple[LongTermMidtermPacketV1, ...],
        *,
        attribute_key: str,
        attribute_value: object,
        limit: int,
    ) -> tuple[LongTermMidtermPacketV1, ...]:
        """Return the newest packets for one scoped attribute subset."""

        bounded_limit = max(0, int(limit))
        if bounded_limit == 0:
            return ()
        matching = list(
            self._matching_packets(
                packets,
                attribute_key=attribute_key,
                attribute_value=attribute_value,
            )
        )
        matching.sort(
            key=lambda packet: (_packet_updated_at(packet), packet.packet_id),
            reverse=True,
        )
        return tuple(matching[:bounded_limit])

    def _load_payload(self) -> dict[str, object] | None:
        """Load the best available validated payload from remote authority or local cache."""

        if self._remote_midterm.enabled():
            try:
                current_head = self._remote_midterm.current_head_payload()
            except LongTermRemoteUnavailableError:
                raise
            except Exception:
                LOGGER.warning("Failed to load remote midterm current head", exc_info=True)
                current_head = None
            if isinstance(current_head, Mapping):
                remote_packets = self._remote_midterm.load_packets()
                remote_payload = self._payload_from_packets(
                    packets=remote_packets,
                    written_at=current_head.get("written_at"),
                )
                try:
                    _write_json_atomic(self.packets_path, remote_payload)
                except OSError:
                    LOGGER.warning(
                        "Loaded remote midterm current head but failed to refresh local cache at %s",
                        self.packets_path,
                        exc_info=True,
                    )
                return remote_payload

        return self._load_local_payload()

    def select_relevant_packets(
        self,
        query_text: str | None,
        *,
        limit: int = 3,
    ) -> tuple[LongTermMidtermPacketV1, ...]:
        """Select midterm packets relevant to one retrieval query.

        Args:
            query_text: Free-text retrieval query. Blank queries return the
                leading packets in stored order.
            limit: Maximum number of packets to return.

        Returns:
            A tuple of midterm packets ordered by selector rank or stored
            order.
        """

        normalized_limit = _normalize_limit(limit)
        if normalized_limit == 0:
            return ()

        clean_query = _normalize_text(query_text)
        if self._remote_midterm.enabled():
            try:
                remote_selected = self._remote_midterm.select_relevant_packets(
                    query_text=clean_query,
                    limit=normalized_limit,
                )
            except LongTermRemoteUnavailableError:
                raise
            except Exception:
                LOGGER.warning("Remote midterm packet selection failed; falling back to hydrated packet ordering", exc_info=True)
            else:
                if not clean_query:
                    return remote_selected
                if remote_selected:
                    filtered_remote = tuple(
                        self._filter_query_relevant_packets(
                            clean_query,
                            selected=list(remote_selected),
                            limit=normalized_limit,
                        )
                    )
                    if filtered_remote:
                        return filtered_remote

        packets = self.load_packets()
        if not packets:
            return ()

        if not clean_query:
            return packets[:normalized_limit]

        try:
            selector = FullTextSelector(
                tuple(
                    FullTextDocument(
                        doc_id=item.packet_id,
                        category="midterm",
                        content=self._packet_search_text(item),
                    )
                    for item in packets
                )
            )
            selected_ids = selector.search(
                clean_query,
                limit=normalized_limit,
                category="midterm",
            )
        except Exception:
            # AUDIT-FIX(#5): Retrieval ranking failure must fall back to deterministic packet ordering, not crash the caller.
            LOGGER.warning("Midterm full-text selection failed; falling back to in-order packets", exc_info=True)
            selected_ids = [item.packet_id for item in packets]

        by_id = {item.packet_id: item for item in packets}
        selected = [by_id[packet_id] for packet_id in selected_ids if packet_id in by_id]
        if not selected:
            selected = list(packets)

        return tuple(
            self._filter_query_relevant_packets(
                clean_query,
                selected=selected,
                limit=normalized_limit,
            )
        )

    def _payload_from_packets(
        self,
        *,
        packets: tuple[LongTermMidtermPacketV1, ...],
        written_at: object = None,
    ) -> dict[str, object]:
        payload = {
            "schema": _MIDTERM_STORE_SCHEMA,
            "version": _MIDTERM_STORE_VERSION,
            "packets": [item.to_payload() for item in sorted(packets, key=lambda row: row.packet_id)],
        }
        normalized_written_at = _normalize_text(written_at if isinstance(written_at, str) else "")
        if normalized_written_at:
            payload["written_at"] = normalized_written_at
        return payload

    def _load_local_payload(self) -> dict[str, object] | None:
        return _validate_payload(_read_json_object(self.packets_path), source=str(self.packets_path))

    def _load_packets_from_payload(
        self,
        payload: Mapping[str, object] | None,
        *,
        source: str,
    ) -> tuple[LongTermMidtermPacketV1, ...]:
        if payload is None:
            return ()
        items = payload.get("packets", [])
        if not isinstance(items, list):
            LOGGER.warning("Midterm store payload has non-list packets field at %s", source)
            return ()
        packets: list[LongTermMidtermPacketV1] = []
        for index, item in enumerate(items):
            if not isinstance(item, dict):
                LOGGER.warning("Skipping non-object midterm packet at index %d from %s", index, source)
                continue
            try:
                packets.append(LongTermMidtermPacketV1.from_payload(item))
            except Exception:
                LOGGER.warning("Skipping invalid midterm packet at index %d from %s", index, source, exc_info=True)
        return tuple(packets)

    def _packet_search_text(self, item: LongTermMidtermPacketV1) -> str:
        parts: list[str] = [
            item.kind,
            item.summary,
            item.details or "",
        ]

        if isinstance(item.query_hints, (list, tuple)):
            parts.extend(hint for hint in item.query_hints if isinstance(hint, str))

        attributes = item.attributes or {}
        if isinstance(attributes, dict):
            for key, value in attributes.items():
                parts.append(str(key))
                if isinstance(value, str):
                    parts.append(value)
                elif isinstance(value, (list, tuple)):
                    parts.extend(str(entry) for entry in value if isinstance(entry, str))
        parts.extend(
            turn_continuity_recall_hints(
                kind=item.kind,
                attributes=attributes if isinstance(attributes, Mapping) else None,
            )
        )

        # AUDIT-FIX(#3): Coerce unexpected scalar fields to strings so partially corrupt packets stay searchable.
        return _normalize_text(" ".join(str(part) for part in parts if part))

    def _filter_query_relevant_packets(
        self,
        query_text: str,
        *,
        selected: list[LongTermMidtermPacketV1],
        limit: int,
    ) -> tuple[LongTermMidtermPacketV1, ...]:
        normalized_limit = _normalize_limit(limit)
        if normalized_limit == 0:
            return ()

        query_terms = _query_match_terms(_safe_retrieval_terms(query_text))
        if not query_terms:
            return tuple(selected[:normalized_limit])

        filtered = [
            item
            for item in selected
            if _has_query_overlap(
                query_terms=query_terms,
                document_terms=_safe_retrieval_terms(self._packet_search_text(item)),
            )
        ]
        if not filtered:
            # AUDIT-FIX(#5): Midterm packets are policy hints, so off-topic false positives are worse than empty recall.
            return ()

        return tuple(filtered[:normalized_limit])

    def _packet_attribute(self, packet: LongTermMidtermPacketV1, key: str) -> object | None:
        """Return one packet attribute value when present."""

        attributes = packet.attributes if isinstance(packet.attributes, Mapping) else {}
        return attributes.get(key)

    def _merged_packets(
        self,
        *,
        primary: tuple[LongTermMidtermPacketV1, ...],
        secondary: tuple[LongTermMidtermPacketV1, ...],
    ) -> tuple[LongTermMidtermPacketV1, ...]:
        """Merge two packet sets by packet id with primary packets winning."""

        merged_by_id = {packet.packet_id: packet for packet in secondary}
        merged_by_id.update({packet.packet_id: packet for packet in primary})
        return tuple(sorted(merged_by_id.values(), key=lambda packet: packet.packet_id))


__all__ = ["LongTermMidtermStore"]
