"""Apply grouped frozen-dataclass updates during config normalization."""

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING

from .parsing import _parse_float

if TYPE_CHECKING:
    from .schema import TwinrConfig


def apply_general_updates(config: "TwinrConfig", updates: Mapping[str, object]) -> None:
    """Apply normalized general, model, camera, and proactive fields."""

    object.__setattr__(config, "long_term_memory_mode", updates["normalized_mode"])
    object.__setattr__(
        config,
        "long_term_memory_remote_required",
        updates["normalized_mode"] == "remote_primary",
    )
    object.__setattr__(config, "default_model", updates["normalized_default_model"])
    object.__setattr__(
        config,
        "streaming_first_word_model",
        updates["normalized_streaming_first_word_model"],
    )
    object.__setattr__(
        config,
        "streaming_supervisor_model",
        updates["normalized_streaming_supervisor_model"],
    )
    object.__setattr__(
        config,
        "streaming_specialist_model",
        updates["normalized_streaming_specialist_model"],
    )
    object.__setattr__(
        config,
        "conversation_closure_model",
        updates["normalized_conversation_closure_model"],
    )
    object.__setattr__(
        config, "openai_search_model", updates["normalized_openai_search_model"]
    )
    object.__setattr__(
        config,
        "voice_orchestrator_ws_url",
        updates["normalized_voice_orchestrator_ws_url"],
    )
    object.__setattr__(
        config, "camera_host_mode", updates["normalized_camera_host_mode"]
    )
    object.__setattr__(
        config,
        "camera_second_pi_base_url",
        updates["normalized_camera_second_pi_base_url"],
    )
    object.__setattr__(
        config,
        "camera_proxy_snapshot_url",
        updates["normalized_camera_proxy_snapshot_url"],
    )
    object.__setattr__(
        config,
        "proactive_remote_camera_base_url",
        updates["normalized_proactive_remote_camera_base_url"],
    )
    object.__setattr__(config, "drone_base_url", updates["normalized_drone_base_url"])
    object.__setattr__(
        config,
        "proactive_vision_provider",
        updates["normalized_proactive_vision_provider"],
    )
    object.__setattr__(
        config,
        "drone_mission_timeout_s",
        _parse_float(config.drone_mission_timeout_s, 45.0, minimum=5.0, maximum=120.0),
    )
    object.__setattr__(
        config,
        "drone_request_timeout_s",
        _parse_float(config.drone_request_timeout_s, 2.0, minimum=0.1, maximum=15.0),
    )
    object.__setattr__(
        config,
        "proactive_quiet_hours_start_local",
        updates["normalized_proactive_quiet_hours_start_local"],
    )
    object.__setattr__(
        config,
        "proactive_quiet_hours_end_local",
        updates["normalized_proactive_quiet_hours_end_local"],
    )


def apply_display_updates(config: "TwinrConfig", updates: Mapping[str, object]) -> None:
    """Apply normalized display and presentation fields."""

    object.__setattr__(config, "display_driver", updates["normalized_display_driver"])
    object.__setattr__(
        config, "display_busy_timeout_s", updates["normalized_display_busy_timeout_s"]
    )
    object.__setattr__(
        config, "display_face_cue_path", updates["normalized_display_face_cue_path"]
    )
    object.__setattr__(
        config, "display_face_cue_ttl_s", updates["normalized_display_face_cue_ttl_s"]
    )
    object.__setattr__(
        config, "display_emoji_cue_path", updates["normalized_display_emoji_cue_path"]
    )
    object.__setattr__(
        config, "display_emoji_cue_ttl_s", updates["normalized_display_emoji_cue_ttl_s"]
    )
    object.__setattr__(
        config,
        "display_ambient_impulse_path",
        updates["normalized_display_ambient_impulse_path"],
    )
    object.__setattr__(
        config,
        "display_ambient_impulse_ttl_s",
        updates["normalized_display_ambient_impulse_ttl_s"],
    )
    object.__setattr__(
        config,
        "display_service_connect_path",
        updates["normalized_display_service_connect_path"],
    )
    object.__setattr__(
        config,
        "display_reserve_generation_model",
        updates["normalized_display_reserve_generation_model"],
    )
    object.__setattr__(
        config,
        "display_reserve_generation_reasoning_effort",
        updates["normalized_display_reserve_generation_reasoning_effort"],
    )
    object.__setattr__(
        config,
        "display_reserve_generation_timeout_seconds",
        updates["normalized_display_reserve_generation_timeout_seconds"],
    )
    object.__setattr__(
        config,
        "display_reserve_generation_max_output_tokens",
        updates["normalized_display_reserve_generation_max_output_tokens"],
    )
    object.__setattr__(
        config,
        "display_reserve_generation_batch_size",
        updates["normalized_display_reserve_generation_batch_size"],
    )
    object.__setattr__(
        config,
        "display_reserve_generation_variants_per_candidate",
        updates["normalized_display_reserve_generation_variants_per_candidate"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_plan_path",
        updates["normalized_display_reserve_bus_plan_path"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_prepared_plan_path",
        updates["normalized_display_reserve_bus_prepared_plan_path"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_maintenance_state_path",
        updates["normalized_display_reserve_bus_maintenance_state_path"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_refresh_after_local",
        updates["normalized_display_reserve_bus_refresh_after_local"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_nightly_enabled",
        bool(config.display_reserve_bus_nightly_enabled),
    )
    object.__setattr__(
        config,
        "display_reserve_bus_nightly_after_local",
        updates["normalized_display_reserve_bus_nightly_after_local"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_nightly_poll_interval_s",
        updates["normalized_display_reserve_bus_nightly_poll_interval_s"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_candidate_limit",
        updates["normalized_display_reserve_bus_candidate_limit"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_items_per_day",
        updates["normalized_display_reserve_bus_items_per_day"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_topic_gap",
        updates["normalized_display_reserve_bus_topic_gap"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_learning_window_days",
        updates["normalized_display_reserve_bus_learning_window_days"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_learning_half_life_days",
        updates["normalized_display_reserve_bus_learning_half_life_days"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_reflection_candidate_limit",
        updates["normalized_display_reserve_bus_reflection_candidate_limit"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_reflection_max_age_days",
        updates["normalized_display_reserve_bus_reflection_max_age_days"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_min_hold_s",
        updates["normalized_display_reserve_bus_min_hold_s"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_base_hold_s",
        updates["normalized_display_reserve_bus_base_hold_s"],
    )
    object.__setattr__(
        config,
        "display_reserve_bus_max_hold_s",
        updates["normalized_display_reserve_bus_max_hold_s"],
    )
    object.__setattr__(
        config,
        "display_attention_refresh_interval_s",
        updates["normalized_display_attention_refresh_interval_s"],
    )
    object.__setattr__(
        config,
        "display_attention_session_focus_hold_s",
        updates["normalized_display_attention_session_focus_hold_s"],
    )
    object.__setattr__(
        config,
        "display_presentation_path",
        updates["normalized_display_presentation_path"],
    )
    object.__setattr__(
        config,
        "display_presentation_ttl_s",
        updates["normalized_display_presentation_ttl_s"],
    )
    object.__setattr__(
        config,
        "display_news_ticker_store_path",
        updates["normalized_display_news_ticker_store_path"],
    )
    object.__setattr__(
        config,
        "display_news_ticker_refresh_interval_s",
        updates["normalized_display_news_ticker_refresh_interval_s"],
    )
    object.__setattr__(
        config,
        "display_news_ticker_rotation_interval_s",
        updates["normalized_display_news_ticker_rotation_interval_s"],
    )
    object.__setattr__(
        config,
        "display_news_ticker_max_items",
        updates["normalized_display_news_ticker_max_items"],
    )
    object.__setattr__(
        config,
        "display_news_ticker_timeout_s",
        updates["normalized_display_news_ticker_timeout_s"],
    )
    object.__setattr__(config, "display_layout", updates["normalized_display_layout"])


def apply_attention_servo_updates(
    config: "TwinrConfig", updates: Mapping[str, object]
) -> None:
    """Apply normalized attention-servo fields."""

    object.__setattr__(
        config, "attention_servo_driver", updates["normalized_attention_servo_driver"]
    )
    object.__setattr__(
        config,
        "attention_servo_control_mode",
        updates["normalized_attention_servo_control_mode"],
    )
    object.__setattr__(
        config,
        "attention_servo_maestro_device",
        updates["normalized_attention_servo_maestro_device"],
    )
    object.__setattr__(
        config,
        "attention_servo_maestro_channel",
        updates["normalized_attention_servo_maestro_channel"],
    )
    object.__setattr__(
        config,
        "attention_servo_peer_base_url",
        updates["normalized_attention_servo_peer_base_url"],
    )
    object.__setattr__(
        config,
        "attention_servo_peer_timeout_s",
        updates["normalized_attention_servo_peer_timeout_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_state_path",
        updates["normalized_attention_servo_state_path"],
    )
    object.__setattr__(
        config,
        "attention_servo_estimated_zero_max_uncertainty_degrees",
        updates["normalized_attention_servo_estimated_zero_max_uncertainty_degrees"],
    )
    object.__setattr__(
        config,
        "attention_servo_estimated_zero_settle_tolerance_degrees",
        updates["normalized_attention_servo_estimated_zero_settle_tolerance_degrees"],
    )
    object.__setattr__(
        config,
        "attention_servo_estimated_zero_speed_scale",
        updates["normalized_attention_servo_estimated_zero_speed_scale"],
    )
    object.__setattr__(
        config,
        "attention_servo_estimated_zero_move_pulse_delta_us",
        updates["normalized_attention_servo_estimated_zero_move_pulse_delta_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_estimated_zero_move_period_s",
        updates["normalized_attention_servo_estimated_zero_move_period_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_estimated_zero_move_duty_cycle",
        updates["normalized_attention_servo_estimated_zero_move_duty_cycle"],
    )
    object.__setattr__(
        config,
        "attention_servo_continuous_return_to_zero_after_s",
        updates["normalized_attention_servo_continuous_return_to_zero_after_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_target_hold_s",
        updates["normalized_attention_servo_target_hold_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_loss_extrapolation_s",
        updates["normalized_attention_servo_loss_extrapolation_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_loss_extrapolation_gain",
        updates["normalized_attention_servo_loss_extrapolation_gain"],
    )
    object.__setattr__(
        config,
        "attention_servo_min_confidence",
        updates["normalized_attention_servo_min_confidence"],
    )
    object.__setattr__(
        config,
        "attention_servo_hold_min_confidence",
        updates["normalized_attention_servo_hold_min_confidence"],
    )
    object.__setattr__(
        config,
        "attention_servo_deadband",
        updates["normalized_attention_servo_deadband"],
    )
    object.__setattr__(
        config,
        "attention_servo_min_pulse_width_us",
        updates["normalized_attention_servo_min_pulse_width_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_center_pulse_width_us",
        updates["normalized_attention_servo_center_pulse_width_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_max_pulse_width_us",
        updates["normalized_attention_servo_max_pulse_width_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_max_step_us",
        updates["normalized_attention_servo_max_step_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_target_smoothing_s",
        updates["normalized_attention_servo_target_smoothing_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_max_velocity_us_per_s",
        updates["normalized_attention_servo_max_velocity_us_per_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_max_acceleration_us_per_s2",
        updates["normalized_attention_servo_max_acceleration_us_per_s2"],
    )
    object.__setattr__(
        config,
        "attention_servo_max_jerk_us_per_s3",
        updates["normalized_attention_servo_max_jerk_us_per_s3"],
    )
    object.__setattr__(
        config,
        "attention_servo_rest_max_velocity_us_per_s",
        updates["normalized_attention_servo_rest_max_velocity_us_per_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_rest_max_acceleration_us_per_s2",
        updates["normalized_attention_servo_rest_max_acceleration_us_per_s2"],
    )
    object.__setattr__(
        config,
        "attention_servo_rest_max_jerk_us_per_s3",
        updates["normalized_attention_servo_rest_max_jerk_us_per_s3"],
    )
    object.__setattr__(
        config,
        "attention_servo_min_command_delta_us",
        updates["normalized_attention_servo_min_command_delta_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_visible_retarget_tolerance_us",
        updates["normalized_attention_servo_visible_retarget_tolerance_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_soft_limit_margin_us",
        updates["normalized_attention_servo_soft_limit_margin_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_idle_release_s",
        updates["normalized_attention_servo_idle_release_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_settled_release_s",
        updates["normalized_attention_servo_settled_release_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_follow_exit_only",
        bool(config.attention_servo_follow_exit_only),
    )
    object.__setattr__(
        config,
        "attention_servo_visible_recenter_interval_s",
        updates["normalized_attention_servo_visible_recenter_interval_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_visible_recenter_center_tolerance",
        updates["normalized_attention_servo_visible_recenter_center_tolerance"],
    )
    object.__setattr__(
        config,
        "attention_servo_mechanical_range_degrees",
        updates["normalized_attention_servo_mechanical_range_degrees"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_follow_max_degrees",
        updates["normalized_attention_servo_exit_follow_max_degrees"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_activation_delay_s",
        updates["normalized_attention_servo_exit_activation_delay_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_settle_hold_s",
        updates["normalized_attention_servo_exit_settle_hold_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_reacquire_center_tolerance",
        updates["normalized_attention_servo_exit_reacquire_center_tolerance"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_visible_edge_threshold",
        updates["normalized_attention_servo_exit_visible_edge_threshold"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_visible_box_edge_threshold",
        updates["normalized_attention_servo_exit_visible_box_edge_threshold"],
    )
    object.__setattr__(
        config,
        "attention_servo_exit_cooldown_s",
        updates["normalized_attention_servo_exit_cooldown_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_continuous_max_speed_degrees_per_s",
        updates["normalized_attention_servo_continuous_max_speed_degrees_per_s"],
    )
    object.__setattr__(
        config,
        "attention_servo_continuous_slow_zone_degrees",
        updates["normalized_attention_servo_continuous_slow_zone_degrees"],
    )
    object.__setattr__(
        config,
        "attention_servo_continuous_stop_tolerance_degrees",
        updates["normalized_attention_servo_continuous_stop_tolerance_degrees"],
    )
    object.__setattr__(
        config,
        "attention_servo_continuous_min_speed_pulse_delta_us",
        updates["normalized_attention_servo_continuous_min_speed_pulse_delta_us"],
    )
    object.__setattr__(
        config,
        "attention_servo_continuous_max_speed_pulse_delta_us",
        updates["normalized_attention_servo_continuous_max_speed_pulse_delta_us"],
    )
