"""Synthetic recipe registry for routing bootstrap corpus generation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping

from .contracts import normalize_route_label
from .user_intent import (
    default_user_intent_for_route_label,
    normalize_user_intent_label,
)


_DEFAULT_NOISE_POOL: tuple[str, ...] = (
    "clean",
    "clean",
    "clean",
    "clean",
    "clean",
    "lowercase",
    "lowercase",
    "no_punct",
    "no_punct",
    "filler",
    "umlaut_flat",
)


@dataclass(frozen=True, slots=True)
class SyntheticRouteTemplate:
    """Describe one utterance surface form for a semantic-router family."""

    key: str
    text: str


@dataclass(frozen=True, slots=True)
class SyntheticRouteRecipe:
    """Describe one transcript family for one semantic-router label."""

    label: str
    family_key: str
    difficulty: str
    templates: tuple[SyntheticRouteTemplate, ...]
    slot_values: Mapping[str, tuple[str, ...]]
    user_label: str | None = None
    noise_pool: tuple[str, ...] = _DEFAULT_NOISE_POOL

    def __post_init__(self) -> None:
        object.__setattr__(self, "label", normalize_route_label(self.label))
        object.__setattr__(
            self,
            "user_label",
            normalize_user_intent_label(
                self.user_label or default_user_intent_for_route_label(self.label)
            ),
        )
        object.__setattr__(self, "family_key", str(self.family_key or "").strip().lower())
        object.__setattr__(self, "difficulty", str(self.difficulty or "standard").strip().lower())
        if not self.family_key:
            raise ValueError("SyntheticRouteRecipe.family_key must not be empty.")
        if not self.templates:
            raise ValueError("SyntheticRouteRecipe.templates must not be empty.")


_ROUTE_RECIPES: tuple[SyntheticRouteRecipe, ...] = (
    SyntheticRouteRecipe(
        label="parametric",
        family_key="stable_explanation",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("plain", "Erklaer mir {concept} in einfachen Worten."),
            SyntheticRouteTemplate("question", "Was bedeutet {concept}?"),
            SyntheticRouteTemplate("function", "Wie funktioniert {concept} genau?"),
            SyntheticRouteTemplate("spoken", "Kannst du mir {concept} kurz erklaeren?"),
        ),
        slot_values={
            "concept": (
                "Photosynthese",
                "Arthrose",
                "Schwerkraft",
                "Inflation",
                "Demenz",
                "Solarenergie",
                "Blutdruck",
                "Cholesterin",
                "WLAN",
                "Impfung",
                "Osteoporose",
                "Diabetes Typ zwei",
                "Lungenentzuendung",
                "Parkinson",
                "Glukose",
                "Waermepumpe",
                "Staatsverschuldung",
                "Datensicherung",
                "Quantencomputer",
                "Verdauung",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="stable_comparison",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("difference", "Was ist der Unterschied zwischen {pair}?"),
            SyntheticRouteTemplate("recognize", "Woran erkennt man den Unterschied zwischen {pair}?"),
            SyntheticRouteTemplate("simple", "Vergleich mir {pair} in einfachen Worten."),
        ),
        slot_values={
            "pair": (
                "Arthrose und Arthritis",
                "Vitamin D und Calcium",
                "Bakterien und Viren",
                "HDMI und USB C",
                "Herzinfarkt und Schlaganfall",
                "Miete und Nebenkosten",
                "Erkaeltung und Grippe",
                "Demenz und Delir",
                "WLAN und Bluetooth",
                "Tablette und Kapsel",
                "Rente und Pension",
                "Insulin und Blutzucker",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="how_to_without_action",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("how_to", "Wie kann man {task}?"),
            SyntheticRouteTemplate("explain_steps", "Erklaer mir Schritt fuer Schritt, wie man {task}."),
            SyntheticRouteTemplate("learn", "Ich moechte lernen, wie man {task}."),
        ),
        slot_values={
            "task": (
                "einen Timer einstellt",
                "einen Brief formuliert",
                "Nudeln kocht",
                "Blutdruck misst",
                "einen Videocall vorbereitet",
                "eine Zimmerpflanze umtopft",
                "eine E Mail beantwortet",
                "eine Einkaufsliste schreibt",
                "das Smartphone lauter stellt",
                "die Heizung entlueftet",
                "einen Verband wechselt",
                "ein Passwort sicher aufschreibt",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="history_and_people",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("who", "Wer war {person}?"),
            SyntheticRouteTemplate("known_for", "Warum ist {person} bekannt?"),
            SyntheticRouteTemplate("when", "Wann lebte {person}?"),
        ),
        slot_values={
            "person": (
                "Marie Curie",
                "Sophie Scholl",
                "Ada Lovelace",
                "Konrad Adenauer",
                "Albert Einstein",
                "Johann Sebastian Bach",
                "Rosalind Franklin",
                "Hildegard von Bingen",
                "Clara Schumann",
                "Otto von Bismarck",
                "Alan Turing",
                "Nelson Mandela",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="translation_and_phrase_help",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("translate", "Wie sagt man {phrase} auf {language}?"),
            SyntheticRouteTemplate("means", "Was heisst {phrase} auf {language}?"),
            SyntheticRouteTemplate("phrase_help", "Uebersetz mir {phrase} in {language}."),
        ),
        slot_values={
            "phrase": (
                "Guten Morgen",
                "Wie geht es dir",
                "Vielen Dank",
                "Ich brauche Hilfe",
                "Bitte langsam sprechen",
                "Wo ist der Bahnhof",
                "Ich moechte einen Kaffee",
                "Bis spaeter",
                "Kannst du mir helfen",
                "Ich komme morgen wieder",
            ),
            "language": ("Italienisch", "Spanisch", "Englisch", "Franzoesisch", "Portugiesisch", "Niederlaendisch"),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="stable_short_explanation",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("short", "Erklaer mir kurz {concept}."),
            SyntheticRouteTemplate("simple", "Kannst du mir einfach erklaeren, was {concept} ist?"),
            SyntheticRouteTemplate("spoken", "Sag mir bitte kurz, was {concept} bedeutet."),
        ),
        slot_values={
            "concept": (
                "Photosynthese",
                "Osteoporose",
                "Demenz",
                "Parkinson",
                "eine Waermepumpe",
                "Inflation",
                "Cholesterin",
                "Blutdruck",
                "Glukose",
                "Datensicherung",
                "Arthrose",
                "Schwerkraft",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="stable_why_questions",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("why", "Warum {phenomenon}?"),
            SyntheticRouteTemplate("wieso", "Wieso {phenomenon}?"),
            SyntheticRouteTemplate("explain_why", "Kannst du mir erklaeren, warum {phenomenon}?"),
        ),
        slot_values={
            "phenomenon": (
                "ist der Himmel blau",
                "schlafen Menschen nachts",
                "wird Fieber anstrengend",
                "steigt der Blutzucker nach dem Essen",
                "werden Blaetter im Herbst gelb",
                "braucht der Koerper Wasser",
                "rostet Eisen",
                "wird man bei einer Erkaeltung muede",
                "ist Bewegung im Alter wichtig",
                "frieren Menschen bei Wind schneller",
                "ist Stress fuer den Blutdruck schlecht",
                "ist ein Helm beim Fahrradfahren sinnvoll",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="general_tech_and_daily_knowledge",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("works", "Wie funktioniert {thing} eigentlich?"),
            SyntheticRouteTemplate("means", "Was genau ist {thing}?"),
            SyntheticRouteTemplate("learn", "Ich moechte verstehen, wie {thing} funktioniert."),
        ),
        slot_values={
            "thing": (
                "ein Router",
                "Bluetooth",
                "ein Akku",
                "ein Kalender",
                "eine To do Liste",
                "ein Passwortmanager",
                "ein Hoergeraet",
                "eine Fernbedienung",
                "ein Thermostat",
                "ein QR Code",
                "ein Blutdruckmessgeraet",
                "ein Smartphone Update",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="parametric",
        family_key="stable_usage_questions",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("usage", "Wofuer braucht man {thing}?"),
            SyntheticRouteTemplate("purpose", "Wozu ist {thing} gut?"),
            SyntheticRouteTemplate("body", "Was macht {system_part}?"),
        ),
        slot_values={
            "thing": (
                "Vitamin B12",
                "eine Brille",
                "eine Impfung",
                "einen Router",
                "eine Waermepumpe",
                "eine Gehhilfe",
                "ein Blutdruckmessgeraet",
                "einen Passwortmanager",
                "eine Patientenverfuegung",
                "eine Einkaufsliste",
                "Bewegung im Alter",
                "ein Hoergeraet",
            ),
            "system_part": (
                "die Schilddruese",
                "die Niere",
                "das Immunsystem",
                "die Lunge",
                "der Blutkreislauf",
                "das Gleichgewichtssystem",
                "die Bauchspeicheldruese",
                "die Verdauung",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="current_weather",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("forecast", "Wie wird das Wetter {time_ref} in {place}?"),
            SyntheticRouteTemplate("umbrella", "Brauche ich {time_ref} in {place} einen Schirm?"),
            SyntheticRouteTemplate("temperature", "Wie warm wird es {time_ref} in {place}?"),
        ),
        slot_values={
            "time_ref": ("heute", "morgen", "am Wochenende", "heute Abend", "morgen Mittag", "in der Nacht"),
            "place": (
                "Berlin",
                "Hamburg",
                "Muenchen",
                "Koeln",
                "Leipzig",
                "Bremen",
                "Dresden",
                "Stuttgart",
                "Frankfurt",
                "Rostock",
                "Freiburg",
                "Hannover",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="current_news",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("today_news", "Was ist {time_ref} in {place} passiert?"),
            SyntheticRouteTemplate("latest_topic", "Gibt es {time_ref} Neuigkeiten zu {topic}?"),
            SyntheticRouteTemplate("summary", "Fass mir die aktuellen Meldungen zu {topic} zusammen."),
        ),
        slot_values={
            "time_ref": ("heute", "gerade", "im Moment", "seit heute Morgen", "heute Abend", "in den letzten Stunden"),
            "place": ("Berlin", "Deutschland", "Europa", "Hamburg", "Muenchen", "Brandenburg", "Sachsen", "Nordrhein Westfalen"),
            "topic": (
                "der Bahn",
                "dem Bundestag",
                "Unwettern",
                "Pflegepolitik",
                "dem Nahverkehr",
                "dem Gesundheitssystem",
                "Renten",
                "Energiepreisen",
                "dem Wetterchaos",
                "dem Flughafen",
                "Pflegenotstand",
                "dem Stromnetz",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="live_schedule_and_opening",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("train", "Wann faehrt der naechste Zug von {origin} nach {destination}?"),
            SyntheticRouteTemplate("open_now", "Hat {place} {time_ref} geoeffnet?"),
            SyntheticRouteTemplate("traffic", "Ist {route} {time_ref} gesperrt?"),
        ),
        slot_values={
            "origin": ("Berlin", "Hamburg", "Koeln", "Leipzig", "Dresden", "Kiel", "Potsdam", "Erfurt"),
            "destination": ("Potsdam", "Hannover", "Dresden", "Bremen", "Magdeburg", "Rostock", "Jena", "Luebeck"),
            "place": (
                "die Apotheke am Markt",
                "das Buero vom Buergerservice",
                "das Hallenbad",
                "der Supermarkt um die Ecke",
                "die Bibliothek",
                "das Rathaus",
                "die Sparkasse am Platz",
                "die Physiopraxis",
            ),
            "time_ref": ("heute", "jetzt", "morgen frueh", "am Sonntag", "heute Nachmittag", "naechste Woche"),
            "route": (
                "die A9",
                "die Ringbahn",
                "die Strecke nach Potsdam",
                "die Linie U2",
                "die A7",
                "die Strecke nach Dresden",
                "die Regionalbahn nach Jena",
                "die S Bahn zum Flughafen",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="current_price_and_availability",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("price_now", "Wie teuer ist {asset} gerade?"),
            SyntheticRouteTemplate("price_current", "Wie hoch ist aktuell der Preis von {asset}?"),
            SyntheticRouteTemplate("availability", "Ist {product} im Moment lieferbar?"),
        ),
        slot_values={
            "asset": ("Heizoel", "Gold", "Bitcoin", "eine Monatskarte", "Strom", "Gas", "Silber", "Diesel", "Superbenzin", "Fernwaerme"),
            "product": (
                "das Diabetes Messgeraet",
                "das Druckerpapier",
                "die Lieblingsschokolade",
                "der Blutdrucksensor",
                "die Tintenpatrone",
                "das Hoergeraet Batteriepack",
                "die Schmerzsalbe",
                "der Wasserfilter",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="safety_lookup",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("meds", "Kann ich {med_a} mit {med_b} zusammen nehmen?"),
            SyntheticRouteTemplate("recall", "Gibt es aktuell Rueckrufe fuer {product}?"),
            SyntheticRouteTemplate("warning", "Gibt es {time_ref} eine Warnung fuer {hazard} in {place}?"),
        ),
        slot_values={
            "med_a": ("Ibuprofen", "Aspirin", "Paracetamol", "Magnesium", "Diclofenac", "Nasenspray", "Johanniskraut", "Vitamin K"),
            "med_b": (
                "Blutverduenner",
                "meine Herztabletten",
                "Antibiotika",
                "Schlafmittel",
                "Insulin",
                "meine Schilddruesentabletten",
                "meine Blutdrucksenker",
                "Cortison",
            ),
            "product": (
                "Raeucherlachs",
                "Erdbeeren",
                "Babynahrung",
                "Blutdrucktabletten",
                "Fertigsalat",
                "Eiscreme",
                "Wurstaufschnitt",
                "Tiefkuehlbeeren",
            ),
            "time_ref": ("heute", "gerade", "fuer morgen", "im Moment"),
            "hazard": ("Sturm", "Glatteis", "Hochwasser", "starke Hitze", "Waldbrand", "Feinstaub", "starker Regen", "Gewitter"),
            "place": ("Berlin", "Hamburg", "Sachsen", "Brandenburg", "Bayern", "Thueringen", "Hessen", "Rheinland Pfalz"),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="current_role_holder",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("derzeit", "Wer ist derzeit {role}?"),
            SyntheticRouteTemplate("aktuell", "Wer ist aktuell {role}?"),
            SyntheticRouteTemplate("amt", "Wer hat im Moment das Amt {role}?"),
        ),
        slot_values={
            "role": (
                "Bundeskanzler",
                "Bundespraesident",
                "Praesident der USA",
                "Buergermeister von Berlin",
                "Chef der Deutschen Bahn",
                "Praesident von Frankreich",
                "EU Kommissionspraesidentin",
                "Ministerpraesident von Bayern",
                "Trainer der deutschen Fussballnationalmannschaft",
                "Praesident der Ukraine",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="live_topic_status",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("what_now", "Was ist aktuell mit {topic} los?"),
            SyntheticRouteTemplate("situation", "Wie ist momentan die Lage bei {topic}?"),
            SyntheticRouteTemplate("new", "Gibt es derzeit etwas Neues zu {topic}?"),
        ),
        slot_values={
            "topic": (
                "der Bahn",
                "den Strompreisen",
                "dem Pflegegeld",
                "den Benzinpreisen",
                "dem Krankenhausstreik",
                "dem Wetter in Norddeutschland",
                "dem Nahverkehr in Berlin",
                "den Unwettern in Bayern",
                "den Rentenplaenen der Regierung",
                "dem Flughafen in Hamburg",
                "dem Wohnungsmarkt",
                "der Lage in der Ukraine",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="web",
        family_key="mutable_role_plain_question",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("plain_role", "Wer ist {role}?"),
            SyntheticRouteTemplate("holds_office", "Wer hat das Amt {role}?"),
            SyntheticRouteTemplate("leads_org", "Wer leitet {institution}?"),
        ),
        slot_values={
            "role": (
                "der Bundeskanzler",
                "der Bundespraesident",
                "der Praesident der USA",
                "der Buergermeister von Berlin",
                "der Ministerpraesident von Bayern",
                "der Chef der Deutschen Bahn",
                "der Praesident von Frankreich",
                "die EU Kommissionspraesidentin",
            ),
            "institution": (
                "die Deutsche Bahn",
                "die Bundesregierung",
                "die EU Kommission",
                "das Kanzleramt",
                "das Bundesgesundheitsministerium",
                "das Weisse Haus",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="personal_fact",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("name", "Wie heisst {relation}?"),
            SyntheticRouteTemplate("birthday", "Wann hat {relation} Geburtstag?"),
            SyntheticRouteTemplate("doctor", "Wie heisst mein {role}?"),
        ),
        slot_values={
            "relation": (
                "meine Enkelin",
                "mein Enkel",
                "meine Tochter",
                "mein Sohn",
                "meine Nachbarin",
                "meine Schwester",
                "mein Bruder",
                "meine Pflegerin",
                "mein Schwiegersohn",
                "meine Enkeltochter",
                "mein Patenkind",
                "meine Freundin aus dem Chor",
            ),
            "role": (
                "Hausarzt",
                "Kardiologe",
                "Physiotherapeut",
                "Friseur",
                "Augenarzt",
                "Pflegedienst",
                "Podologe",
                "Zahnarzt",
                "Orthopaede",
                "Fahrdienst",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="preferences",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("favorite", "Welchen {item} mag ich am liebsten?"),
            SyntheticRouteTemplate("music", "Welche Musik hoere ich gern, wenn ich unruhig bin?"),
            SyntheticRouteTemplate("routine", "Welchen Tee trinke ich abends am liebsten?"),
        ),
        slot_values={
            "item": ("Kuchen", "Tee", "Saft", "Pullover", "Filmgenre", "Suppe", "Marmelade", "Musikrichtung", "Kissen", "Schal", "Buchgenre", "Brot"),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="household_location",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("where", "Wo haben wir {object_name} hingelegt?"),
            SyntheticRouteTemplate("kept", "Wo liegt {object_name} normalerweise?"),
            SyntheticRouteTemplate("stored", "In welchem Schrank bewahren wir {object_name} auf?"),
        ),
        slot_values={
            "object_name": (
                "den Zweitschluessel",
                "die Impfausweise",
                "das Ladegeraet",
                "die Winterdecken",
                "die Taschenlampe",
                "das Rezeptheft",
                "die Ersatzbrille",
                "den Garagenschluessel",
                "den Reisepass",
                "die Notfallmappe",
                "das Hoergeraet Ladegeraet",
                "die Kerzen",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="prior_conversation",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("remember_plan", "Was hatten wir ueber {topic} festgehalten?"),
            SyntheticRouteTemplate("reminder_context", "Woran wollte ich mich {time_ref} erinnern?"),
            SyntheticRouteTemplate("trip_plan", "Welchen Plan hatten wir fuer {event}?"),
        ),
        slot_values={
            "topic": (
                "den Urlaub",
                "den Arztbesuch",
                "den Einkauf",
                "die Geburtstagsfeier",
                "die Steuerunterlagen",
                "die Gartenarbeit",
                "die Reha",
                "das Abendessen mit der Familie",
                "den Zahnarzttermin",
                "die Bahnfahrt",
            ),
            "time_ref": ("morgen", "naechste Woche", "am Wochenende", "im April", "im Mai", "naechsten Monat", "an Weihnachten", "uebermorgen"),
            "event": (
                "Ostern",
                "den Familienbesuch",
                "den Ausflug",
                "den Geburtstag von Anna",
                "das Sommerfest",
                "den Besuch vom Pflegedienst",
                "die Reise nach Hamburg",
                "mein Jubilaeum",
                "den Chorabend",
                "den Arzttermin am Montag",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="personal_health_notes",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("allergies", "Welche Allergien habe ich?"),
            SyntheticRouteTemplate("meds", "Welche Tabletten nehme ich morgens?"),
            SyntheticRouteTemplate("notes", "Was steht in meinen Notizen zu {topic}?"),
        ),
        slot_values={
            "topic": (
                "meinem Ruecken",
                "meinem Schlaf",
                "meinem Blutdruck",
                "meiner Ernaehrung",
                "meinen Knien",
                "meinem Gleichgewicht",
                "meiner Haut",
                "meinem Magen",
                "meiner Bewegung",
                "meinem Blutzucker",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="contact_details",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("phone", "Welche Telefonnummer hat {contact}?"),
            SyntheticRouteTemplate("address", "Welche Adresse habe ich fuer {contact} gespeichert?"),
            SyntheticRouteTemplate("details", "Welche Kontaktdaten habe ich zu {contact} notiert?"),
        ),
        slot_values={
            "contact": (
                "meine Tochter",
                "meinen Sohn",
                "meine Schwester",
                "meinen Hausarzt",
                "den Pflegedienst",
                "Frau Schneider",
                "meinen Nachbarn",
                "meine Enkelin",
                "meinen Fahrdienst",
                "die Apotheke",
                "meinen Physiotherapeuten",
                "den Hausmeister",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="personal_routines",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("when_usually", "Wann mache ich normalerweise {routine}?"),
            SyntheticRouteTemplate("day", "An welchem Tag ist bei mir {routine} dran?"),
            SyntheticRouteTemplate("time", "Zu welcher Uhrzeit mache ich meistens {routine}?"),
        ),
        slot_values={
            "routine": (
                "die Gymnastik",
                "den Wocheneinkauf",
                "das Blumen giessen",
                "den Blutdruck",
                "den Anruf bei meiner Tochter",
                "das Medikamente sortieren",
                "den Spaziergang",
                "das Tagebuch schreiben",
                "das Hoergeraet Laden",
                "den Muell rausbringen",
                "das Bett beziehen",
                "den Chorabend",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="known_people_preferences",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("likes", "Was mag {person} besonders gern?"),
            SyntheticRouteTemplate("prefers", "Worueber freut sich {person} am meisten?"),
            SyntheticRouteTemplate("notes", "Was hatten wir ueber {person} festgehalten?"),
        ),
        slot_values={
            "person": (
                "Anna",
                "Karl",
                "meine Tochter",
                "mein Enkel",
                "Frau Schneider",
                "der Pfleger Jens",
                "meine Nachbarin",
                "mein Sohn",
                "Oma Lotte",
                "Onkel Peter",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="short_known_people_preferences",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("short_like", "Was mag {person}?"),
            SyntheticRouteTemplate("likes", "Was mag {person} gern?"),
            SyntheticRouteTemplate("happy", "Worueber freut sich {person}?"),
        ),
        slot_values={
            "person": (
                "Anna",
                "Karl",
                "meine Tochter",
                "mein Sohn",
                "meine Schwester",
                "mein Enkel",
                "Frau Schneider",
                "der Pfleger Jens",
                "meine Nachbarin",
                "mein Hausarzt",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="remembered_people_context",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("about_person", "Was hatten wir ueber {person} besprochen?"),
            SyntheticRouteTemplate("notes", "Was weiss ich ueber {person}?"),
            SyntheticRouteTemplate("stored", "Was hatten wir uns zu {person} notiert?"),
        ),
        slot_values={
            "person": (
                "Anna",
                "Karl",
                "meine Tochter",
                "meinen Sohn",
                "meine Schwester",
                "meinen Nachbarn",
                "Frau Schneider",
                "den Pfleger Jens",
                "meine Enkelin",
                "meinen Hausarzt",
                "den Fahrdienst",
                "den Physiotherapeuten",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="person_reason_memory",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("call_reason", "Warum hat {person} angerufen?"),
            SyntheticRouteTemplate("visit_reason", "Warum kommt {person} zu mir?"),
            SyntheticRouteTemplate("wanted_reason", "Weshalb wollte {person} mich sprechen?"),
        ),
        slot_values={
            "person": (
                "Anna",
                "meine Tochter",
                "mein Sohn",
                "meine Schwester",
                "der Pflegedienst",
                "der Fahrdienst",
                "Frau Schneider",
                "mein Hausarzt",
                "meine Enkelin",
                "mein Nachbar",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="memory",
        family_key="personal_reason_context",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("why_visit", "Warum kommt {person} zu mir?"),
            SyntheticRouteTemplate("why_call", "Warum wollte {person} mich anrufen?"),
            SyntheticRouteTemplate("why_note", "Weshalb hatten wir {topic} fuer mich festgehalten?"),
        ),
        slot_values={
            "person": (
                "Anna",
                "meine Tochter",
                "der Pflegedienst",
                "mein Sohn",
                "Frau Schneider",
                "mein Hausarzt",
                "der Fahrdienst",
                "meine Enkelin",
            ),
            "topic": (
                "den Arzttermin",
                "den Einkauf",
                "die Reise nach Hamburg",
                "die Medikamente",
                "den Besuch am Wochenende",
                "den Zahnarzttermin",
                "den Chorabend",
                "die Geburtstagsfeier",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        user_label="persoenlich",
        family_key="personal_schedule_lookup",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("appointments", "Was habe ich {time_ref} fuer Termine?"),
            SyntheticRouteTemplate("calendar", "Was steht {time_ref} in meinem Kalender?"),
            SyntheticRouteTemplate("visit", "Kommt {time_ref} jemand zu mir?"),
        ),
        slot_values={
            "time_ref": (
                "heute",
                "morgen",
                "heute Nachmittag",
                "heute Abend",
                "am Montag",
                "naechste Woche",
                "diese Woche",
                "uebermorgen",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        user_label="persoenlich",
        family_key="personal_pending_state",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("meds_open", "Habe ich {time_ref} noch Medikamente offen?"),
            SyntheticRouteTemplate("reminders", "Welche Erinnerung habe ich {time_ref}?"),
            SyntheticRouteTemplate("tasks", "Welche Aufgaben habe ich {time_ref} noch offen?"),
        ),
        slot_values={
            "time_ref": (
                "heute",
                "heute Abend",
                "morgen",
                "fuer heute",
                "fuer morgen",
                "am Wochenende",
                "naechste Woche",
                "heute Nacht",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        user_label="persoenlich",
        family_key="personal_day_overview",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("today", "Was ist {time_ref} bei mir los?"),
            SyntheticRouteTemplate("for_me", "Was steht {time_ref} fuer mich an?"),
            SyntheticRouteTemplate("overview", "Was habe ich {time_ref} noch vor?"),
        ),
        slot_values={
            "time_ref": (
                "heute",
                "heute Nachmittag",
                "heute Abend",
                "morgen",
                "am Montag",
                "diese Woche",
                "naechste Woche",
                "uebermorgen",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        user_label="persoenlich",
        family_key="personal_short_schedule_status",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("have_plan", "Hab ich {time_ref} was vor?"),
            SyntheticRouteTemplate("planned", "Ist {time_ref} bei mir was geplant?"),
            SyntheticRouteTemplate("coming_up", "Steht {time_ref} bei mir etwas an?"),
        ),
        slot_values={
            "time_ref": (
                "heute",
                "heute Nachmittag",
                "heute Abend",
                "morgen",
                "am Montag",
                "diese Woche",
                "naechste Woche",
                "uebermorgen",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        user_label="persoenlich",
        family_key="care_support_visits",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("when_arrive", "Wann kommt {visitor} zu mir?"),
            SyntheticRouteTemplate("is_scheduled", "Ist {visitor} {time_ref} bei mir eingetragen?"),
            SyntheticRouteTemplate("coming", "Kommt {visitor} {time_ref} zu mir?"),
        ),
        slot_values={
            "visitor": (
                "der Pflegedienst",
                "meine Tochter",
                "mein Sohn",
                "der Fahrdienst",
                "mein Hausarzt",
                "die Physiotherapie",
                "meine Enkelin",
                "Frau Schneider",
            ),
            "time_ref": (
                "heute",
                "morgen",
                "heute Abend",
                "heute Nachmittag",
                "am Montag",
                "diese Woche",
                "naechste Woche",
                "uebermorgen",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="house_state_snapshot",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("house_now", "Was ist im Haus los?"),
            SyntheticRouteTemplate("doors", "Ist {door} gerade offen?"),
            SyntheticRouteTemplate("room_state", "Wie ist der Status im {room}?"),
        ),
        slot_values={
            "door": (
                "die Haustuer",
                "die Balkontuer",
                "das Kuechenfenster",
                "das Schlafzimmerfenster",
                "die Kellertuer",
                "die Terrassentuer",
            ),
            "room": (
                "Wohnzimmer",
                "Kueche",
                "Flur",
                "Schlafzimmer",
                "Bad",
                "Arbeitszimmer",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="home_environment_state",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("temperature", "Wie warm ist es gerade im {room}?"),
            SyntheticRouteTemplate("light", "Ist im {room} noch Licht an?"),
            SyntheticRouteTemplate("appliance", "Ist {appliance} gerade an?"),
        ),
        slot_values={
            "room": (
                "Wohnzimmer",
                "Schlafzimmer",
                "Bad",
                "Flur",
                "Kueche",
                "Arbeitszimmer",
                "Gaestezimmer",
                "Keller",
            ),
            "appliance": (
                "der Herd",
                "der Fernseher",
                "die Kaffeemaschine",
                "die Heizdecke",
                "der Ventilator",
                "die Waschmaschine",
                "der Trockner",
                "die Nachttischlampe",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="doorbell_and_presence_check",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("doorbell", "Hat es gerade geklingelt?"),
            SyntheticRouteTemplate("door", "War jemand an der Haustuer?"),
            SyntheticRouteTemplate("arrival", "Ist eben jemand gekommen?"),
        ),
        slot_values={},
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="home_scene_control",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("lights", "Mach {device} bitte {state}."),
            SyntheticRouteTemplate("switch", "Schalte {device} {state}."),
            SyntheticRouteTemplate("set", "Stell {device} auf {state}."),
        ),
        slot_values={
            "device": (
                "das Licht im Wohnzimmer",
                "die Lampe im Flur",
                "den Fernseher",
                "die Heizung im Bad",
                "den Ventilator",
                "die Steckdose an der Kaffeemaschine",
                "das Radio",
                "die Nachttischlampe",
            ),
            "state": (
                "an",
                "aus",
                "leiser",
                "lauter",
                "waermer",
                "kuehler",
                "niedriger",
                "hoeher",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="timers_and_reminders",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("timer", "Stell einen Timer auf {duration}."),
            SyntheticRouteTemplate("alarm", "Mach mir einen Wecker fuer {clock_time}."),
            SyntheticRouteTemplate("remind", "Erinnere mich {time_ref} an {task}."),
        ),
        slot_values={
            "duration": ("5 Minuten", "10 Minuten", "15 Minuten", "20 Minuten", "25 Minuten", "30 Minuten", "45 Minuten", "eine Stunde", "zwei Stunden", "90 Minuten"),
            "clock_time": (
                "7 Uhr",
                "8 Uhr 30",
                "morgen frueh um 6",
                "heute Abend um 21 Uhr",
                "14 Uhr",
                "16 Uhr 15",
                "morgen um 9",
                "Freitag um 11",
                "naechste Woche Montag um 8",
                "heute Nacht um 23 Uhr",
            ),
            "time_ref": (
                "heute Abend",
                "morgen frueh",
                "naechsten Dienstag",
                "am Wochenende",
                "heute Nachmittag",
                "uebermorgen",
                "am Montagmorgen",
                "jeden Abend um 20 Uhr",
                "naechsten Monat",
                "in einer Stunde",
            ),
            "task": (
                "die Tabletten",
                "den Anruf bei meiner Tochter",
                "das Blumen giessen",
                "den Arzttermin",
                "das Wasser trinken",
                "die Waesche",
                "die Gymnastikuebungen",
                "den Blutdruck",
                "den Muell",
                "das Abendessen",
                "den Spaziergang",
                "das Hoergeraet Laden",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="print_and_write",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("print", "Druck {item}."),
            SyntheticRouteTemplate("list", "Schreib {item} auf die Liste."),
            SyntheticRouteTemplate("note", "Notier dir bitte {item}."),
        ),
        slot_values={
            "item": (
                "meine Einkaufsliste",
                "den Arzttermin fuer Freitag",
                "Milch und Brot",
                "die Telefonnummer vom Pflegedienst",
                "die Rezepte fuer diese Woche",
                "meine Medikamente fuer morgen",
                "den Einkaufszettel fuer Ostern",
                "die Notiz fuer den Hausarzt",
                "die Adresse von Frau Schneider",
                "meine To do Liste fuer heute",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="device_control",
        difficulty="standard",
        templates=(
            SyntheticRouteTemplate("louder", "Mach bitte lauter."),
            SyntheticRouteTemplate("quieter", "Stell die Lautstaerke leiser."),
            SyntheticRouteTemplate("play", "Starte {media_item}."),
            SyntheticRouteTemplate("stop", "Stoppe {media_item}."),
        ),
        slot_values={
            "media_item": (
                "das Radio",
                "meine Abendmusik",
                "die Entspannungsmusik",
                "die Nachrichten",
                "die klassische Musik",
                "das Hoerbuch",
                "die Wettervorhersage",
                "meine Lieblingsplaylist",
                "die Morgenmusik",
                "die Naturgeraesche",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="live_state_check",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("printer", "Pruef, ob der {device} verbunden ist."),
            SyntheticRouteTemplate("status", "Schau nach, ob {status_item}."),
            SyntheticRouteTemplate("show", "Zeig mir {system_view}."),
        ),
        slot_values={
            "device": ("Drucker", "Bildschirm", "WLAN Adapter", "Lautsprecher", "Scanner", "Mikrofon", "Kopfhoerer", "Touchdisplay", "Router", "Ladestation"),
            "status_item": (
                "noch Erinnerungen offen sind",
                "der Drucker Papier hat",
                "eine neue Nachricht angekommen ist",
                "mein naechster Termin schon eingetragen ist",
                "das WLAN stabil ist",
                "heute noch Medikamente offen sind",
                "die Einkaufsliste leer ist",
                "eine Druckwarteschlange haengt",
                "der Wecker aktiv ist",
                "das Mikrofon verbunden ist",
            ),
            "system_view": (
                "meine naechste Erinnerung",
                "meine offenen Aufgaben",
                "die heutigen Termine",
                "die letzten Notizen",
                "den Status vom Drucker",
                "meine Erinnerungen fuer morgen",
                "die Einkaufsliste",
                "die Wecker fuer diese Woche",
            ),
        },
    ),
    SyntheticRouteRecipe(
        label="tool",
        family_key="messages_and_actions",
        difficulty="boundary",
        templates=(
            SyntheticRouteTemplate("message", "Schick {person} die Nachricht {message}."),
            SyntheticRouteTemplate("call", "Ruf bitte {person} an."),
            SyntheticRouteTemplate("open", "Oeffne {view}."),
        ),
        slot_values={
            "person": (
                "meine Tochter",
                "meinen Sohn",
                "den Pflegedienst",
                "Frau Schneider",
                "meine Schwester",
                "meinen Enkel",
                "den Nachbarn",
                "den Hausarzt",
                "den Fahrdienst",
                "meine Enkelin",
            ),
            "message": (
                "ich komme spaeter",
                "bitte bring Brot mit",
                "ich denke an dich",
                "der Termin ist bestaetigt",
                "ich bin schon unterwegs",
                "bitte ruf mich spaeter an",
                "ich brauche morgen Hilfe",
                "der Druck ist fertig",
                "wir sehen uns am Sonntag",
                "die Medikamente sind bestellt",
            ),
            "view": (
                "meine Erinnerungen",
                "die Einkaufsliste",
                "die Druckvorschau",
                "die Notizen",
                "den Kalender",
                "die Aufgabenliste",
                "die Nachrichten",
                "die Druckwarteschlange",
            ),
        },
    ),
)
