"""Expose Twinr's shared integration package surface.

Re-export the common contracts, builtin provider packages, runtime helpers,
and dashboard-facing utilities from stable import paths used across Twinr.
"""

from twinr.integrations.adapter import CallableIntegrationAdapter, IntegrationAdapter
from twinr.integrations.catalog import BUILTIN_MANIFESTS, builtin_manifests, manifest_for_id, manifests_for_domain
from twinr.integrations.calendar import CalendarAdapterSettings, CalendarEvent, CalendarReader, ICSCalendarSource, ReadOnlyCalendarAdapter
from twinr.integrations.email import (
    ApprovedEmailContacts,
    EmailAdapterSettings,
    EmailContact,
    EmailDraft,
    EmailMailboxAdapter,
    EmailMessageSummary,
    IMAPMailboxConfig,
    IMAPMailboxReader,
    MailSender,
    MailboxReader,
    SMTPMailSender,
    SMTPMailSenderConfig,
)
from twinr.integrations.smarthome import (
    SmartHomeAdapterSettings,
    SmartHomeCommand,
    SmartHomeController,
    SmartHomeEntity,
    SmartHomeEntityClass,
    SmartHomeEntityProvider,
    SmartHomeEvent,
    SmartHomeEventBatch,
    SmartHomeEventKind,
    SmartHomeIntegrationAdapter,
    SmartHomeSensorStream,
)
from twinr.integrations.smarthome.hue import (
    HueBridgeClient,
    HueBridgeConfig,
    HueSmartHomeProvider,
    build_hue_smart_home_provider,
)
from twinr.integrations.models import (
    ConfirmationMode,
    DataSensitivity,
    IntegrationAction,
    IntegrationDecision,
    IntegrationDomain,
    IntegrationManifest,
    IntegrationOperation,
    IntegrationRequest,
    IntegrationResult,
    RequestOrigin,
    RiskLevel,
    SafetyProfile,
    SecretReference,
    SecretStorage,
)
from twinr.integrations.policy import SafeIntegrationPolicy, stricter_confirmation
from twinr.integrations.registry import (
    IntegrationNotFoundError,
    IntegrationPolicyError,
    IntegrationRegistry,
    IntegrationRegistryError,
)
from twinr.integrations.runtime import (
    CALENDAR_AGENDA_INTEGRATION_ID,
    EMAIL_APP_PASSWORD_ENV_KEY,
    EMAIL_MAILBOX_INTEGRATION_ID,
    IntegrationReadiness,
    ManagedIntegrationsRuntime,
    build_calendar_agenda_adapter,
    build_email_mailbox_adapter,
    build_managed_integrations,
    validate_calendar_source,
)
from twinr.integrations.store import ManagedIntegrationConfig, TwinrIntegrationStore, integration_store_path
from twinr.integrations.web_automation_families import (
    IntegrationAutomationFamilyBlock,
    IntegrationAutomationFamilyProvider,
    integration_automation_family_providers,
)

__all__ = [
    "BUILTIN_MANIFESTS",
    "ApprovedEmailContacts",
    "CALENDAR_AGENDA_INTEGRATION_ID",
    "CalendarAdapterSettings",
    "CalendarEvent",
    "CalendarReader",
    "CallableIntegrationAdapter",
    "ConfirmationMode",
    "DataSensitivity",
    "EMAIL_APP_PASSWORD_ENV_KEY",
    "EMAIL_MAILBOX_INTEGRATION_ID",
    "EmailAdapterSettings",
    "EmailContact",
    "EmailDraft",
    "EmailMailboxAdapter",
    "EmailMessageSummary",
    "ICSCalendarSource",
    "IMAPMailboxConfig",
    "IMAPMailboxReader",
    "IntegrationAction",
    "IntegrationAdapter",
    "IntegrationDecision",
    "IntegrationDomain",
    "IntegrationManifest",
    "IntegrationNotFoundError",
    "IntegrationOperation",
    "IntegrationPolicyError",
    "IntegrationRegistry",
    "IntegrationRegistryError",
    "IntegrationRequest",
    "IntegrationResult",
    "IntegrationReadiness",
    "MailSender",
    "ManagedIntegrationConfig",
    "ManagedIntegrationsRuntime",
    "MailboxReader",
    "ReadOnlyCalendarAdapter",
    "RequestOrigin",
    "RiskLevel",
    "SMTPMailSender",
    "SMTPMailSenderConfig",
    "SafeIntegrationPolicy",
    "SafetyProfile",
    "SecretReference",
    "SecretStorage",
    "SmartHomeAdapterSettings",
    "SmartHomeCommand",
    "SmartHomeController",
    "SmartHomeEntity",
    "SmartHomeEntityClass",
    "SmartHomeEntityProvider",
    "SmartHomeEvent",
    "SmartHomeEventBatch",
    "SmartHomeEventKind",
    "SmartHomeIntegrationAdapter",
    "SmartHomeSensorStream",
    "TwinrIntegrationStore",
    "HueBridgeClient",
    "HueBridgeConfig",
    "HueSmartHomeProvider",
    "IntegrationAutomationFamilyBlock",
    "IntegrationAutomationFamilyProvider",
    "builtin_manifests",
    "build_calendar_agenda_adapter",
    "build_email_mailbox_adapter",
    "build_hue_smart_home_provider",
    "build_managed_integrations",
    "integration_automation_family_providers",
    "integration_store_path",
    "manifest_for_id",
    "manifests_for_domain",
    "stricter_confirmation",
    "validate_calendar_source",
]
