"""Expose the ``twinr.proactive`` package surface and child package boundary.

Import from ``twinr.proactive`` when runtime workflows need one compatibility
surface for proactive governance, monitor wiring, social-trigger scoring, and
wakeword helpers. Reach into ``twinr.proactive.runtime``,
``twinr.proactive.social``, ``twinr.proactive.event_fusion``,
``twinr.proactive.governance``, or ``twinr.proactive.wakeword`` when the
caller only works inside one proactive subsystem so this package root stays a
thin re-export boundary.
"""

from twinr.proactive.governance import (
    ProactiveGovernor,
    ProactiveGovernorCandidate,
    ProactiveGovernorDecision,
    ProactiveGovernorHistoryEntry,
    ProactiveGovernorReservation,
)
from twinr.proactive.runtime import (
    PresenceSessionController,
    PresenceSessionSnapshot,
    ProactiveCoordinator,
    ProactiveMonitorService,
    build_default_proactive_monitor,
)
from twinr.proactive.social import (
    AmbientAudioObservationProvider,
    NullAudioObservationProvider,
    OpenAIVisionObservationProvider,
    OpenAIProactiveVisionReviewer,
    ProactiveAudioSnapshot,
    ProactiveVisionFrameBuffer,
    ProactiveVisionReview,
    ProactiveVisionSnapshot,
    SocialAudioObservation,
    SocialBodyPose,
    SocialFineHandGesture,
    SocialGestureEvent,
    SocialObservation,
    SocialPersonZone,
    SocialTriggerDecision,
    SocialTriggerEngine,
    SocialTriggerEvaluation,
    SocialTriggerPriority,
    SocialTriggerThresholds,
    SocialVisionObservation,
    TriggerScoreEvidence,
    WeightedTriggerScore,
    bool_score,
    hold_progress,
    is_reviewable_image_trigger,
    is_safety_trigger,
    parse_proactive_vision_review_text,
    parse_vision_observation_text,
    proactive_observation_facts,
    proactive_prompt_mode,
    recent_progress,
    weighted_trigger_score,
)
def _raise_missing_optional_wakeword_dependency(*args, **kwargs):
    """Raise the deferred optional wakeword import failure on first real use."""

    raise ModuleNotFoundError(
        "Optional wakeword dependency unavailable during import. "
        "Install the missing dependency or avoid the optional wakeword backend/tooling path."
    ) from _OPTIONAL_WAKEWORD_IMPORT_ERROR


_OPTIONAL_WAKEWORD_IMPORT_ERROR: ModuleNotFoundError | None = None

try:
    from twinr.proactive.wakeword import (
        DEFAULT_WAKEWORD_PHRASES,
        OpenWakeWordPrediction,
        OpenWakeWordStreamingMonitor,
        SttWakewordVerifier,
        WakewordAmbientGuardResult,
        WakewordAmbientGuardSpec,
        WakewordAutotuneRecommendation,
        WakewordBaseModelTrainingReport,
        WakewordCalibrationProfile,
        WakewordCalibrationStore,
        WakewordDecision,
        WakewordDecisionPolicy,
        WakewordEvalEntry,
        WakewordEvalMetrics,
        WakewordEvalReport,
        WakewordKwsAssetBundle,
        WakewordVerifierTrainingReport,
        WakewordMatch,
        WakewordOpenWakeWordFrameSpotter,
        WakewordOpenWakeWordSpotter,
        WakewordPhraseSpotter,
        WakewordPromotionReport,
        WakewordPromotionSpec,
        WakewordPromotionSuiteResult,
        WakewordPromotionSuiteSpec,
        PreparedWekwsExperiment,
        PreparedWekwsSplit,
        WakewordSequenceCaptureVerifier,
        WakewordSequenceVerifier,
        WakewordSequenceVerifierTrainingReport,
        WakewordSherpaOnnxFrameSpotter,
        WakewordSherpaOnnxSpotter,
        WakewordStreamEvalReport,
        WakewordStreamDetection,
        WakewordTrainingCommand,
        WakewordTrainingPlan,
        WakewordVerification,
        WakewordWekwsAssetBundle,
        WakewordWekwsFrameSpotter,
        WakewordWekwsModelConfig,
        WakewordWekwsSpotter,
        WekwsRecipeSpec,
        WakewordAcceptanceMetricPlan,
        available_wekws_recipe_specs,
        append_wakeword_capture_label,
        apply_wakeword_calibration,
        autotune_wakeword_profile,
        build_default_wakeword_training_plan,
        evaluate_wakeword_stream_entries,
        load_eval_manifest,
        load_wakeword_promotion_spec,
        load_labeled_ops_captures,
        match_wakeword_transcript,
        normalize_wakeword_backend,
        normalize_detector_label,
        normalize_wakeword_verifier_mode,
        phrase_from_detector_label,
        render_wakeword_training_plan_markdown,
        run_wakeword_promotion_eval,
        run_wakeword_eval,
        run_wakeword_stream_eval,
        prepare_wekws_experiment,
        train_wakeword_base_model_from_dataset_root,
        train_wakeword_custom_verifier_from_manifest,
        train_wakeword_sequence_verifier_from_manifest,
        wakeword_primary_prompt,
    )
except ModuleNotFoundError as exc:
    _OPTIONAL_WAKEWORD_IMPORT_ERROR = exc
    from twinr.proactive.wakeword.calibration import (
        WakewordCalibrationProfile,
        WakewordCalibrationStore,
        apply_wakeword_calibration,
    )
    from twinr.proactive.wakeword.kws import (
        WakewordKwsAssetBundle,
        WakewordSherpaOnnxFrameSpotter,
        WakewordSherpaOnnxSpotter,
    )
    from twinr.proactive.wakeword.matching import (
        DEFAULT_WAKEWORD_PHRASES,
        WakewordMatch,
        WakewordPhraseSpotter,
        match_wakeword_transcript,
        normalize_detector_label,
        phrase_from_detector_label,
        wakeword_primary_prompt,
    )
    from twinr.proactive.wakeword.policy import (
        SttWakewordVerifier,
        WakewordDecision,
        WakewordDecisionPolicy,
        WakewordVerification,
        normalize_wakeword_backend,
        normalize_wakeword_verifier_mode,
    )
    from twinr.proactive.wakeword.spotter import (
        OpenWakeWordPrediction,
        WakewordOpenWakeWordFrameSpotter,
        WakewordOpenWakeWordSpotter,
    )
    from twinr.proactive.wakeword.stream import OpenWakeWordStreamingMonitor, WakewordStreamDetection

    for _name in (
        "WakewordAmbientGuardResult",
        "WakewordAmbientGuardSpec",
        "WakewordAutotuneRecommendation",
        "WakewordBaseModelTrainingReport",
        "WakewordEvalEntry",
        "WakewordEvalMetrics",
        "WakewordEvalReport",
        "WakewordVerifierTrainingReport",
        "WakewordPromotionReport",
        "WakewordPromotionSpec",
        "WakewordPromotionSuiteResult",
        "WakewordPromotionSuiteSpec",
        "PreparedWekwsExperiment",
        "PreparedWekwsSplit",
        "WakewordSequenceCaptureVerifier",
        "WakewordSequenceVerifier",
        "WakewordSequenceVerifierTrainingReport",
        "WakewordStreamEvalReport",
        "WakewordTrainingCommand",
        "WakewordTrainingPlan",
        "WakewordWekwsAssetBundle",
        "WakewordWekwsFrameSpotter",
        "WakewordWekwsModelConfig",
        "WakewordWekwsSpotter",
        "WekwsRecipeSpec",
        "WakewordAcceptanceMetricPlan",
        "available_wekws_recipe_specs",
        "append_wakeword_capture_label",
        "autotune_wakeword_profile",
        "build_default_wakeword_training_plan",
        "evaluate_wakeword_stream_entries",
        "load_eval_manifest",
        "load_wakeword_promotion_spec",
        "load_labeled_ops_captures",
        "render_wakeword_training_plan_markdown",
        "run_wakeword_promotion_eval",
        "run_wakeword_eval",
        "run_wakeword_stream_eval",
        "prepare_wekws_experiment",
        "train_wakeword_base_model_from_dataset_root",
        "train_wakeword_custom_verifier_from_manifest",
        "train_wakeword_sequence_verifier_from_manifest",
    ):
        globals()[_name] = _raise_missing_optional_wakeword_dependency

__all__ = [
    "AmbientAudioObservationProvider",
    "NullAudioObservationProvider",
    "OpenWakeWordPrediction",
    "OpenWakeWordStreamingMonitor",
    "OpenAIVisionObservationProvider",
    "OpenAIProactiveVisionReviewer",
    "ProactiveGovernor",
    "ProactiveGovernorCandidate",
    "ProactiveGovernorDecision",
    "ProactiveGovernorHistoryEntry",
    "ProactiveGovernorReservation",
    "ProactiveAudioSnapshot",
    "ProactiveCoordinator",
    "ProactiveVisionFrameBuffer",
    "ProactiveVisionReview",
    "ProactiveMonitorService",
    "ProactiveVisionSnapshot",
    "PresenceSessionController",
    "PresenceSessionSnapshot",
    "SocialAudioObservation",
    "SocialBodyPose",
    "SocialFineHandGesture",
    "SocialGestureEvent",
    "SocialObservation",
    "SocialPersonZone",
    "SocialTriggerDecision",
    "SocialTriggerEngine",
    "SocialTriggerEvaluation",
    "SocialTriggerPriority",
    "SocialTriggerThresholds",
    "SocialVisionObservation",
    "TriggerScoreEvidence",
    "SttWakewordVerifier",
    "WakewordAmbientGuardResult",
    "WakewordAmbientGuardSpec",
    "WakewordAutotuneRecommendation",
    "WakewordBaseModelTrainingReport",
    "WakewordCalibrationProfile",
    "WakewordCalibrationStore",
    "WakewordDecision",
    "WakewordDecisionPolicy",
    "WakewordEvalEntry",
    "WakewordEvalMetrics",
    "WakewordEvalReport",
    "WakewordKwsAssetBundle",
    "WakewordVerifierTrainingReport",
    "WakewordMatch",
    "WakewordOpenWakeWordFrameSpotter",
    "WakewordOpenWakeWordSpotter",
    "WakewordPhraseSpotter",
    "WakewordPromotionReport",
    "WakewordPromotionSpec",
    "WakewordPromotionSuiteResult",
    "WakewordPromotionSuiteSpec",
    "PreparedWekwsExperiment",
    "PreparedWekwsSplit",
    "WakewordSequenceCaptureVerifier",
    "WakewordSequenceVerifier",
    "WakewordSequenceVerifierTrainingReport",
    "WakewordSherpaOnnxFrameSpotter",
    "WakewordSherpaOnnxSpotter",
    "WakewordStreamEvalReport",
    "WakewordStreamDetection",
    "WakewordTrainingCommand",
    "WakewordTrainingPlan",
    "WakewordVerification",
    "WakewordWekwsAssetBundle",
    "WakewordWekwsFrameSpotter",
    "WakewordWekwsModelConfig",
    "WakewordWekwsSpotter",
    "WekwsRecipeSpec",
    "WakewordAcceptanceMetricPlan",
    "WeightedTriggerScore",
    "available_wekws_recipe_specs",
    "append_wakeword_capture_label",
    "apply_wakeword_calibration",
    "autotune_wakeword_profile",
    "build_default_wakeword_training_plan",
    "bool_score",
    "build_default_proactive_monitor",
    "DEFAULT_WAKEWORD_PHRASES",
    "evaluate_wakeword_stream_entries",
    "hold_progress",
    "is_reviewable_image_trigger",
    "load_eval_manifest",
    "load_wakeword_promotion_spec",
    "load_labeled_ops_captures",
    "parse_vision_observation_text",
    "parse_proactive_vision_review_text",
    "recent_progress",
    "is_safety_trigger",
    "match_wakeword_transcript",
    "normalize_wakeword_backend",
    "normalize_detector_label",
    "normalize_wakeword_verifier_mode",
    "phrase_from_detector_label",
    "render_wakeword_training_plan_markdown",
    "proactive_observation_facts",
    "proactive_prompt_mode",
    "run_wakeword_promotion_eval",
    "run_wakeword_eval",
    "run_wakeword_stream_eval",
    "prepare_wekws_experiment",
    "train_wakeword_base_model_from_dataset_root",
    "train_wakeword_custom_verifier_from_manifest",
    "train_wakeword_sequence_verifier_from_manifest",
    "wakeword_primary_prompt",
    "weighted_trigger_score",
]
